<?php
/**
 * @file
 * Code for the Farm Bee feature.
 */

include_once 'farm_bee.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_bee_farm_ui_entities() {
  return array(
    'farm_asset' => array(
      'bee_colony' => array(
        'label' => t('Bee Colony'),
        'label_plural' => t('Bee Colonies'),
        'view' => 'farm_bee_colonies',
      ),
    ),
  );
}

/**
 * Implements hook_farm_log_categories().
 */
function farm_bee_farm_log_categories() {

  // Provide an "Bees" log category.
  return array('Bees');
}
